### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by AOoligei** [S-rz/THINE#1]
Hello, I have read your paper, it's really a nice work. Now I want to run this project, but I can not find the source data according to your paper. Can you upload the data you have used? Thanks a lot!

**Comment by S-rz** [comment]
Hi, thank you for your interest in our work, and I have uploaded Aminer and DBLP datasets.

**Comment by AOoligei** [comment]
> Hi, thank you for your interest in our work, and I have uploaded Aminer and DBLP datasets.

Thanks for your reply, 
I have another question in my later research, in Heterogeneous_Rec.py, you want to predict the next connection, so how should I design the format of this Yelp/u_b_rec.txt file, if I want to test the model, should I set this edge list as a fully connected network.
In addition I don't understand whether the recommended connection has a timestamp, or does it not distinguish the time, and predicts the connection at all subsequent times,
Hope you can help me out, thank you.
